name: Publish Library

# When a release is published
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./Brotli.NET
    steps:
    - uses: actions/checkout@v4
    - name: Get version
      run: |
        echo "VERSION=${{ github.event.release.tag_name }}" >> $env:GITHUB_ENV
        echo "Building with ${{ env.VERSION }}"
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Brotli.Core --configuration Release --no-restore -p:Version=${{ env.VERSION }}
    - name: Pack
      run: dotnet pack Brotli.Core --output nupkgs --configuration Release -p:Version=${{ env.VERSION }}
    - name: Nuget Publish
      run: dotnet nuget push nupkgs\*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json